In [1]:
import numpy as np

In [3]:
array_a = np.array([0,1,2,3])

print(array_a)
print(type(array_a))

[0 1 2 3]
<class 'numpy.ndarray'>


In [4]:
print(array_a.dtype)

int64


In [11]:
# np array must be in same type, else it will become string
array_b = np.array([0, 'one', 2, 3,4])
print(array_b)


['0' 'one' '2' '3' '4']


In [12]:
print(array_a.shape)
print(array_b.shape)

(4,)
(5,)


In [15]:
print(array_a[0])
print(array_b[-1])
print(array_a[1:3])

0
4
[1 2]


In [17]:
# np allows set NaN
array_with_nan_value = np.array([1.2, 3.2, 4.0, 5.3, np.nan, 3.9])

print(array_with_nan_value)
print(array_with_nan_value.dtype)

# the nan can preserve the array's dtype

[1.2 3.2 4.  5.3 nan 3.9]
float64


In [31]:
### Multidimensional
array_c = np.array([[1,2,3], [4,5,6]])
print(array_c)
print(array_c.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [32]:
# Reshape
print(array_c.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [33]:
print(array_c.reshape(1,6))

[[1 2 3 4 5 6]]


In [34]:
print(len(array_c.reshape(1,6).shape))

2


In [35]:
# reduce and reshape axes
print(array_c.reshape(6,))

print(array_c.flatten())

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [36]:
print(array_c.transpose())

[[1 4]
 [2 5]
 [3 6]]


In [37]:
array_d = np.array(range(1,10)).reshape(3,3)
print(array_d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [46]:
print(array_d[0, :]) # [x, y] x=>row, y=> column
print(array_d[1:, 1:])

[1 2 3]
[[5 6]
 [8 9]]


In [47]:
# Toy problem
mini_business_ids = np.array(range(1, 171))

mini_id_matrix = mini_business_ids.reshape(17, 10)

print(mini_id_matrix)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]
 [101 102 103 104 105 106 107 108 109 110]
 [111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130]
 [131 132 133 134 135 136 137 138 139 140]
 [141 142 143 144 145 146 147 148 149 150]
 [151 152 153 154 155 156 157 158 159 160]
 [161 162 163 164 165 166 167 168 169 170]]


In [48]:
# so when i want 10 rows 17 cols
mini_id_matrix = mini_business_ids.reshape(10, 17)

print(mini_id_matrix)

[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17]
 [ 18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34]
 [ 35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51]
 [ 52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68]
 [ 69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85]
 [ 86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101 102]
 [103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136]
 [137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153]
 [154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170]]


In [49]:
print(mini_id_matrix.transpose())

[[  1  18  35  52  69  86 103 120 137 154]
 [  2  19  36  53  70  87 104 121 138 155]
 [  3  20  37  54  71  88 105 122 139 156]
 [  4  21  38  55  72  89 106 123 140 157]
 [  5  22  39  56  73  90 107 124 141 158]
 [  6  23  40  57  74  91 108 125 142 159]
 [  7  24  41  58  75  92 109 126 143 160]
 [  8  25  42  59  76  93 110 127 144 161]
 [  9  26  43  60  77  94 111 128 145 162]
 [ 10  27  44  61  78  95 112 129 146 163]
 [ 11  28  45  62  79  96 113 130 147 164]
 [ 12  29  46  63  80  97 114 131 148 165]
 [ 13  30  47  64  81  98 115 132 149 166]
 [ 14  31  48  65  82  99 116 133 150 167]
 [ 15  32  49  66  83 100 117 134 151 168]
 [ 16  33  50  67  84 101 118 135 152 169]
 [ 17  34  51  68  85 102 119 136 153 170]]


In [50]:
# Elementwise
x = np.array([[1.0, 2.0], [3.0, 4.0]])

y = np.array([[2.0, 5.0], [6.0, 7.0]])

In [51]:
print(x + y)

[[ 3.  7.]
 [ 9. 11.]]


In [52]:
print(x - y)

[[-1. -3.]
 [-3. -3.]]


In [53]:
print(x/y)

[[0.5        0.4       ]
 [0.5        0.57142857]]


In [54]:
print( x % y)

[[1. 2.]
 [3. 4.]]


In [55]:
# scalar
print( x + 2 )

[[3. 4.]
 [5. 6.]]


In [60]:
more_x = np.array([[1.0, 2.0, 5.0], [3.0, 4.0, 6.0]])
more_y = np.array([[2.0, 5.0, 6.0], [6.0, 7.0, 8.0]])

print(more_y + more_x)
print(more_y % 2)

[[ 3.  7. 11.]
 [ 9. 11. 14.]]
[[0. 1. 0.]
 [0. 1. 0.]]


In [61]:
np.power(x, 3)

array([[ 1.,  8.],
       [27., 64.]])

In [62]:
print(x)
print(np.sum(x))

[[1. 2.]
 [3. 4.]]
10.0


In [66]:
# axis=0 across column
# axis=1 across row
print(np.sum(x, axis=0))

[4. 6.]


In [67]:
# Random
sample = np.random.randint(low=0, high=10, size=64)
print(sample)

[4 8 4 1 4 2 0 3 6 9 0 5 8 9 4 5 1 4 8 4 6 2 5 4 2 2 1 5 1 5 3 7 7 9 1 9 0
 6 0 2 7 0 4 1 4 8 6 2 0 9 8 9 0 8 3 6 4 0 3 2 5 6 6 7]


In [68]:
print(sample.reshape(8, 8))

[[4 8 4 1 4 2 0 3]
 [6 9 0 5 8 9 4 5]
 [1 4 8 4 6 2 5 4]
 [2 2 1 5 1 5 3 7]
 [7 9 1 9 0 6 0 2]
 [7 0 4 1 4 8 6 2]
 [0 9 8 9 0 8 3 6]
 [4 0 3 2 5 6 6 7]]


In [69]:
generated_matrix = np.random.randint(0, 10, (8, 8))
print(generated_matrix)

[[1 3 4 3 6 2 6 4]
 [0 5 8 8 0 2 8 1]
 [4 6 6 9 8 2 1 4]
 [3 7 2 2 1 7 9 7]
 [7 2 9 3 5 1 1 9]
 [1 0 3 4 5 3 9 5]
 [5 0 7 9 7 2 0 3]
 [5 0 1 9 2 5 1 0]]


In [73]:
np.random.seed(1337)

generated_matrix = np.random.randint(0, 10, (8, 8))
print(generated_matrix)

[[7 8 7 9 7 2 2 4]
 [8 9 6 6 7 8 1 6]
 [6 2 2 9 8 1 7 3]
 [1 3 9 3 4 8 8 7]
 [9 4 1 6 4 4 2 5]
 [7 4 2 3 9 2 4 8]
 [6 3 8 8 7 4 3 2]
 [9 1 2 0 3 8 2 1]]


In [74]:
np.random.seed(55)

# randomly select 5 elements from the first column
print(np.random.choice(generated_matrix[:, 0], 5))

# take note the triple 7, meanwhile first column only has two 7

[7 6 9 7 7]


In [76]:
np.random.seed(55)
print(np.random.choice(generated_matrix[:, 0], 5, replace=False))

[9 9 6 8 1]
